# -*- coding: utf-8 -*-
"""Villager reactions when the player places blocks inside a village (by rep tier)."""

P = "villagediplomacy.react.place"


def _tier(en, es, block, tier, lines_en, lines_es):
    for i, t in enumerate(lines_en):
        en[f"{P}.{block}.{tier}.{i}"] = t
    for i, t in enumerate(lines_es):
        es[f"{P}.{block}.{tier}.{i}"] = t


def _block(en, es, block, w_en, w_es, n_en, n_es, u_en, u_es):
    _tier(en, es, block, "welcome", w_en, w_es)
    _tier(en, es, block, "neutral", n_en, n_es)
    _tier(en, es, block, "unwelcome", u_en, u_es)


def inject_place_react(en, es):
    _block(
        en,
        es,
        "bed",
        [
            "§a[Villager] Make yourself at home, friend!",
            "§a[Villager] Feel free to rest here anytime.",
            "§a[Villager] Your own bed! You're part of the village now.",
            "§a[Villager] Welcome home!",
            "§7[Villager] *smiles warmly* Good spot.",
            "§a[Villager] Glad to have you living with us!",
        ],
        [
            "§a[Aldeano] ¡Ponte cómodo, amigo!",
            "§a[Aldeano] Siéntete libre de descansar aquí cuando quieras.",
            "§a[Aldeano] ¡Tu propia cama! Ya eres parte de la aldea.",
            "§a[Aldeano] ¡Bienvenido a casa!",
            "§7[Aldeano] *sonríe cálidamente* Es un buen lugar.",
            "§a[Aldeano] ¡Es bueno tenerte viviendo con nosotros!",
        ],
        [
            "§e[Villager] Getting comfortable, huh?",
            "§e[Villager] Oh, claiming a bed already...",
            "§e[Villager] Planning to stay a while?",
            "§7[Villager] *nods* Fine place for a bed.",
            "§e[Villager] Moving in?",
            "§e[Villager] Building here now?",
        ],
        [
            "§e[Aldeano] ¿¡Poniéndote cómodo!?",
            "§e[Aldeano] Ah, reclamando una cama ya veo...",
            "§e[Aldeano] ¿¡Planeas quedarte un tiempo!?",
            "§7[Aldeano] *asiente* Es un buen lugar para una cama.",
            "§e[Aldeano] ¿¡Instalándote!?",
            "§e[Aldeano] ¿¡Ahora construyes aquí!?",
        ],
        [
            "§c[Villager] What do you think you're doing!?",
            "§c[Villager] Hey! You're not welcome to build here!",
            "§7[Villager] *glares suspiciously*",
            "§c[Villager] We don't want you living here!",
            "§c[Villager] You can't just move in like that!",
            "§c[Villager] Take that out of our village!",
        ],
        [
            "§c[Aldeano] ¿¡Qué estás haciendo!?",
            "§c[Aldeano] ¡Oye! ¡No eres bienvenido a construir aquí!",
            "§7[Aldeano] *mira con furia sospechosamente*",
            "§c[Aldeano] ¡No queremos que vivas aquí!",
            "§c[Aldeano] ¿¡Crees que puedes mudarte así sin más!?",
            "§c[Aldeano] ¡Saca eso de nuestra aldea!",
        ],
    )

    _block(
        en,
        es,
        "chest",
        [
            "§a[Villager] Setting up storage? Smart!",
            "§a[Villager] Keep your valuables safe, friend.",
            "§7[Villager] Perfect spot for a chest.",
            "§a[Villager] You're really making this home!",
            "§a[Villager] Need help organizing your things?",
            "§a[Villager] A chest! Staying long-term, then?",
        ],
        [
            "§a[Aldeano] ¿¡Preparando almacenamiento!? ¡Inteligente!",
            "§a[Aldeano] Mantén tus objetos valiosos seguros, amigo.",
            "§7[Aldeano] Ese es un lugar perfecto para un cofre.",
            "§a[Aldeano] ¡Realmente estás haciendo de esto tu hogar!",
            "§a[Aldeano] ¿¡Necesitas ayuda organizando tus cosas!?",
            "§a[Aldeano] ¿¡Un cofre! ¿¡Te quedas a largo plazo entonces!?",
        ],
        [
            "§e[Villager] Stashing your stuff here?",
            "§e[Villager] Ah, setting up storage...",
            "§7[Villager] Solid place for a chest.",
            "§e[Villager] Making this your home?",
            "§e[Villager] You're really settling in...",
            "§e[Villager] Planning to stay?",
        ],
        [
            "§e[Aldeano] ¿¡Almacenando tus pertenencias aquí!?",
            "§e[Aldeano] Ah, preparando almacenamiento...",
            "§7[Aldeano] Ese es un buen lugar para un cofre.",
            "§e[Aldeano] ¿¡Haciendo de esto tu hogar!?",
            "§e[Aldeano] Realmente te estás instalando...",
            "§e[Aldeano] ¿¡Planeas quedarte!?",
        ],
        [
            "§c[Villager] What's going in that chest!?",
            "§c[Villager] We don't want YOUR stuff here!",
            "§c[Villager] Taking over our village, are you!?",
            "§7[Villager] *watches suspiciously*",
            "§c[Villager] Don't think we won't check that!",
            "§c[Villager] You're up to something...",
        ],
        [
            "§c[Aldeano] ¿¡Qué hay en ese cofre!?",
            "§c[Aldeano] ¡No queremos TUS cosas aquí!",
            "§c[Aldeano] ¿¡Te apoderas de nuestra aldea, verdad!?",
            "§7[Aldeano] *observa sospechosamente*",
            "§c[Aldeano] ¡No creas que no revisaremos eso!",
            "§c[Aldeano] Estás tramando algo...",
        ],
    )

    _block(
        en,
        es,
        "furnace",
        [
            "§a[Villager] A furnace! We could use more industry!",
            "§a[Villager] Excellent! A new workshop!",
            "§a[Villager] You're helping the village economy!",
            "§7[Villager] That'll be useful for everyone.",
            "§a[Villager] Good thinking—we need more crafters.",
            "§a[Villager] You're really helping the village grow!",
        ],
        [
            "§a[Aldeano] ¿¡Un horno! ¡Podríamos usar más industria!",
            "§a[Aldeano] ¡Excelente! ¡Un nuevo taller!",
            "§a[Aldeano] ¡Estás contribuyendo a la economía de la aldea!",
            "§7[Aldeano] Eso será útil para todos.",
            "§a[Aldeano] ¡Buen pensamiento! Necesitamos más artesanos.",
            "§a[Aldeano] ¡Realmente estás ayudando a crecer la aldea!",
        ],
        [
            "§e[Villager] Putting up a furnace?",
            "§e[Villager] Oh, going to smelt!",
            "§e[Villager] Planning to craft here?",
            "§7[Villager] That'll come in handy.",
            "§e[Villager] Building your own workshop?",
            "§e[Villager] Going to make something?",
        ],
        [
            "§e[Aldeano] ¿¡Preparando un horno!?",
            "§e[Aldeano] ¡Oh, vas a fundir!",
            "§e[Aldeano] ¿¡Planeas fabricar aquí!?",
            "§7[Aldeano] Eso será útil.",
            "§e[Aldeano] ¿¡Construyendo tu propio taller!?",
            "§e[Aldeano] ¿¡Vas a hacer algo!?",
        ],
        [
            "§c[Villager] What are you building!?",
            "§c[Villager] We don't need YOUR furnaces!",
            "§c[Villager] Stop cluttering our village!",
            "§7[Villager] *frowns deeply*",
            "§c[Villager] You're not the smith here!",
            "§c[Villager] Take that somewhere else!",
        ],
        [
            "§c[Aldeano] ¿¡Qué estás construyendo!?",
            "§c[Aldeano] ¡No necesitamos TUS hornos!",
            "§c[Aldeano] ¡Deja de saturar nuestra aldea!",
            "§7[Aldeano] *frunce el ceño profundamente*",
            "§c[Aldeano] ¡No eres herrero aquí!",
            "§c[Aldeano] ¡Lleva eso a otro lugar!",
        ],
    )

    _block(
        en,
        es,
        "crafting",
        [
            "§a[Villager] A crafting table! Perfect!",
            "§a[Villager] Oh, a workshop—great idea!",
            "§a[Villager] A true crafter!",
            "§7[Villager] We appreciate skilled artisans.",
            "§a[Villager] The village benefits from your skills!",
            "§a[Villager] You're becoming quite the craftsman!",
        ],
        [
            "§a[Aldeano] ¿¡Una mesa de crafteo! ¡Perfecto!",
            "§a[Aldeano] ¡Oh, preparando un taller! ¡Buena idea!",
            "§a[Aldeano] ¡Eres un verdadero artesano!",
            "§7[Aldeano] Apreciamos a los artesanos hábiles.",
            "§a[Aldeano] ¡La aldea se beneficia de tus habilidades!",
            "§a[Aldeano] ¡Te estás convirtiendo en todo un artesano!",
        ],
        [
            "§e[Villager] A crafting table! Very useful.",
            "§e[Villager] Oh, setting up shop!",
            "§e[Villager] Getting comfortable.",
            "§7[Villager] Smart thinking.",
            "§e[Villager] Planning to make something?",
            "§e[Villager] Crafting here?",
        ],
        [
            "§e[Aldeano] ¿¡Una mesa de crafteo! Muy útil.",
            "§e[Aldeano] ¡Oh, preparando un taller!",
            "§e[Aldeano] Realmente te estás poniendo cómodo.",
            "§7[Aldeano] Pensamiento inteligente.",
            "§e[Aldeano] ¿¡Planeas hacer algo!?",
            "§e[Aldeano] ¿¡Vas a fabricar aquí!?",
        ],
        [
            "§c[Villager] We have our OWN crafting tables!",
            "§c[Villager] You're not part of this village!",
            "§c[Villager] Stop building on our land!",
            "§7[Villager] *crosses arms*",
            "§c[Villager] You're not welcome to craft here!",
            "§c[Villager] Move that table elsewhere!",
        ],
        [
            "§c[Aldeano] ¡Tenemos nuestras PROPIAS mesas de crafteo!",
            "§c[Aldeano] ¡No eres parte de esta aldea!",
            "§c[Aldeano] ¡Deja de construir en nuestro territorio!",
            "§7[Aldeano] *cruza los brazos*",
            "§c[Aldeano] ¡No eres bienvenido a fabricar aquí!",
            "§c[Aldeano] ¡Lleva esa mesa a otro lugar!",
        ],
    )

    _block(
        en,
        es,
        "bell",
        [
            "§a[Villager] A bell! That'll help coordinate everyone!",
            "§a[Villager] Excellent! Now we can signal each other!",
            "§a[Villager] You're thinking like a true villager!",
            "§7[Villager] *impressed* Very thoughtful.",
            "§a[Villager] A bell for the community—thank you!",
        ],
        [
            "§a[Aldeano] ¡Una campana! ¡Eso ayudará a coordinar a todos!",
            "§a[Aldeano] ¡Excelente! ¡Ahora podemos señalarnos entre nosotros!",
            "§a[Aldeano] ¡Estás pensando como un verdadero aldeano!",
            "§7[Aldeano] *impresionado* Eso es muy considerado.",
            "§a[Aldeano] ¡Una campana para la comunidad! ¡Gracias!",
        ],
        [
            "§e[Villager] A bell? Interesting...",
            "§7[Villager] That's... unusual.",
            "§e[Villager] Planning to call meetings?",
            "§e[Villager] A bell could be useful.",
            "§7[Villager] *looks curious*",
        ],
        [
            "§e[Aldeano] ¿¡Una campana! Interesante...",
            "§7[Aldeano] Eso es... inusual.",
            "§e[Aldeano] ¿¡Planeas llamar reuniones!?",
            "§e[Aldeano] ¡Una campana! Eso podría ser útil.",
            "§7[Aldeano] *mira con curiosidad*",
        ],
        [
            "§c[Villager] Don't you DARE ring it!",
            "§c[Villager] We ALREADY have a bell!",
            "§c[Villager] You're not in charge here!",
            "§7[Villager] *glares*",
            "§c[Villager] That's OUR gathering symbol!",
        ],
        [
            "§c[Aldeano] ¡No te ATREVAS a tocarla!",
            "§c[Aldeano] ¡Ya TENEMOS una campana!",
            "§c[Aldeano] ¡Tú no estás a cargo aquí!",
            "§7[Aldeano] *mira con furia*",
            "§c[Aldeano] ¡Ese es NUESTRO símbolo de reunión!",
        ],
    )

    _block(
        en,
        es,
        "brewing",
        [
            "§a[Villager] A brewing stand! An alchemist!",
            "§a[Villager] Oh! You know potions!",
            "§a[Villager] We could use someone with your skills!",
            "§7[Villager] *very impressed*",
            "§a[Villager] An alchemist in our village—wonderful!",
            "§a[Villager] Your potions will help everyone!",
        ],
        [
            "§a[Aldeano] ¡Un soporte de pociones! ¡Eres alquimista!",
            "§a[Aldeano] ¡Oh! ¿¡Sabes hacer pociones!",
            "§a[Aldeano] ¡Podríamos usar alguien con tus habilidades!",
            "§7[Aldeano] *muy impresionado*",
            "§a[Aldeano] ¡Un alquimista en nuestra aldea! ¡Maravilloso!",
            "§a[Aldeano] ¡Tus pociones beneficiarán a todos!",
        ],
        [
            "§e[Villager] A brewing stand! Fancy!",
            "§e[Villager] Oh! Making potions?",
            "§e[Villager] You know alchemy?",
            "§7[Villager] *impressed*",
            "§e[Villager] That's pretty advanced!",
            "§e[Villager] An alchemist, eh?",
        ],
        [
            "§e[Aldeano] ¿¡Un soporte de pociones! ¡Elegante!",
            "§e[Aldeano] ¡Oh! ¿¡Vas a hacer pociones!",
            "§e[Aldeano] ¿¡Conoces alquimia!?",
            "§7[Aldeano] *impresionado*",
            "§e[Aldeano] ¡Eso es bastante avanzado!",
            "§e[Aldeano] ¿¡Un alquimista, eh!?",
        ],
        [
            "§c[Villager] What potions are you brewing!?",
            "§c[Villager] We don't trust your alchemy!",
            "§c[Villager] Probably making POISON!",
            "§7[Villager] *steps back nervously*",
            "§c[Villager] Keep your suspicious brews away!",
            "§c[Villager] You're up to no good!",
        ],
        [
            "§c[Aldeano] ¿¡Qué pociones estás preparando!",
            "§c[Aldeano] ¡No confiamos en tu alquimia!",
            "§c[Aldeano] ¡Probablemente estás haciendo VENENO!",
            "§7[Aldeano] *retrocede nerviosamente*",
            "§c[Aldeano] ¡Mantén tus pociones sospechosas lejos de nosotros!",
            "§c[Aldeano] ¡Estás tramando algo malo!",
        ],
    )

    _block(
        en,
        es,
        "enchanting",
        [
            "§d[Villager] An enchanting table! Incredible!",
            "§d[Villager] You practice magic! Amazing!",
            "§a[Villager] This will make the village much stronger!",
            "§7[Villager] *stares at the runes in awe*",
            "§d[Villager] A true mage among us—an honor!",
            "§a[Villager] Your magic will protect us all!",
        ],
        [
            "§d[Aldeano] ¡Una mesa de encantamientos! ¡Increíble!",
            "§d[Aldeano] ¡Practicas magia! ¡Asombroso!",
            "§a[Aldeano] ¡Esto hará la aldea mucho más fuerte!",
            "§7[Aldeano] *mira con asombro las runas mágicas*",
            "§d[Aldeano] ¡Un verdadero mago entre nosotros! ¡Es un honor!",
            "§a[Aldeano] ¡Tu experiencia mágica nos protegerá a todos!",
        ],
        [
            "§d[Villager] An enchanting table! Wow!",
            "§e[Villager] You know magic!?",
            "§7[Villager] *stares at the floating book*",
            "§e[Villager] That's... real magic!",
            "§d[Villager] I've never seen one up close!",
            "§e[Villager] You're a wizard!?",
        ],
        [
            "§d[Aldeano] ¡Una mesa de encantamientos! ¡Wow!",
            "§e[Aldeano] ¿¡Conoces magia!?",
            "§7[Aldeano] *mira el libro flotante con asombro*",
            "§e[Aldeano] ¡Eso es... eso es magia real!",
            "§d[Aldeano] ¡Nunca había visto una de cerca!",
            "§e[Aldeano] ¿¡Eres un mago!?",
        ],
        [
            "§c[Villager] Dark magic! I knew you were trouble!",
            "§c[Villager] We don't want witchcraft here!",
            "§c[Villager] That table gives me the creeps...",
            "§7[Villager] *warding gesture*",
            "§c[Villager] You're cursing our land!",
            "§c[Villager] Take your dark arts elsewhere!",
        ],
        [
            "§c[Aldeano] ¡Magia oscura! ¡Sabía que eras problemático!",
            "§c[Aldeano] ¡No queremos brujería en nuestra aldea!",
            "§c[Aldeano] Esa mesa me da mala espina...",
            "§7[Aldeano] *hace un gesto de protección*",
            "§c[Aldeano] ¡Estás maldiciendo nuestra tierra!",
            "§c[Aldeano] ¡Lleva tus artes oscuras a otro lugar!",
        ],
    )

    _block(
        en,
        es,
        "bookshelf",
        [
            "§6[Villager] Books! You're building a library!",
            "§a[Villager] Knowledge is precious—thank you!",
            "§7[Villager] The children will love having books.",
            "§6[Villager] A scholar! We're lucky to have you.",
            "§a[Villager] You're enriching our culture!",
            "§6[Villager] A library! Truly civilized.",
        ],
        [
            "§6[Aldeano] ¡Libros! ¡Estás construyendo una biblioteca!",
            "§a[Aldeano] ¡El conocimiento es precioso! ¡Gracias!",
            "§7[Aldeano] A los niños les encantará tener libros para leer.",
            "§6[Aldeano] ¡Un erudito! Tenemos suerte de tenerte.",
            "§a[Aldeano] ¡Estás enriqueciendo nuestra cultura!",
            "§6[Aldeano] ¡Una librería! Realmente eres civilizado.",
        ],
        [
            "§e[Villager] A library! You like to read?",
            "§7[Villager] Books are valuable around here.",
            "§e[Villager] Building a personal library?",
            "§6[Villager] *examines the books curiously*",
            "§e[Villager] Collecting knowledge?",
            "§7[Villager] Quite scholarly.",
        ],
        [
            "§e[Aldeano] ¡Una librería! ¿¡Te gusta leer!?",
            "§7[Aldeano] Los libros son valiosos por aquí.",
            "§e[Aldeano] ¿¡Construyendo una biblioteca personal!?",
            "§6[Aldeano] *examina los libros con curiosidad*",
            "§e[Aldeano] ¿¡Coleccionas conocimiento!?",
            "§7[Aldeano] Eso es bastante erudito.",
        ],
        [
            "§c[Villager] Stealing our knowledge traditions!",
            "§c[Villager] Those books belong in OUR library!",
            "§c[Villager] You don't deserve our wisdom!",
            "§7[Villager] *frowns at the shelves*",
            "§c[Villager] Trying to look smart, huh!",
            "§c[Villager] We know you can't even read!",
        ],
        [
            "§c[Aldeano] ¡Robando nuestras tradiciones de conocimiento!",
            "§c[Aldeano] ¡Esos libros deberían estar en NUESTRA biblioteca!",
            "§c[Aldeano] ¡No mereces nuestra sabiduría!",
            "§7[Aldeano] *frunce el ceño ante la librería*",
            "§c[Aldeano] Intentas parecer inteligente, ¿¡verdad!",
            "§c[Aldeano] ¡Sabemos que ni siquiera puedes leer!",
        ],
    )

    _block(
        en,
        es,
        "lectern",
        [
            "§6[Villager] A lectern! For reading and study!",
            "§a[Villager] Setting up a proper study!",
            "§7[Villager] The mark of a true scholar.",
            "§6[Villager] Will you share your knowledge with us?",
            "§a[Villager] A lectern shows dedication to learning!",
        ],
        [
            "§6[Aldeano] ¡Un atril! ¡Para leer y estudiar!",
            "§a[Aldeano] ¡Estás preparando un estudio apropiado!",
            "§7[Aldeano] La marca de un verdadero erudito.",
            "§6[Aldeano] ¿¡Compartirás tu conocimiento con nosotros!",
            "§a[Aldeano] ¡Un atril muestra dedicación al aprendizaje!",
        ],
        [
            "§e[Villager] A lectern! Planning to read?",
            "§7[Villager] That's for displaying books, right?",
            "§e[Villager] Setting up a study area?",
            "§6[Villager] *nods approvingly*",
            "§e[Villager] You value knowledge, I see.",
        ],
        [
            "§e[Aldeano] ¡Un atril! ¿¡Planeas leer!",
            "§7[Aldeano] Eso es para exhibir libros, ¿¡verdad!",
            "§e[Aldeano] ¿¡Preparando un área de estudio!",
            "§6[Aldeano] *asiente con aprobación*",
            "§e[Aldeano] Valoras el conocimiento, veo.",
        ],
        [
            "§c[Villager] Who do you think you are, a teacher!?",
            "§c[Villager] We don't need YOUR lessons!",
            "§c[Villager] Pretending to be educated...",
            "§7[Villager] *scoffs*",
            "§c[Villager] You can't teach us anything!",
        ],
        [
            "§c[Aldeano] ¿¡Quién te crees que eres, un maestro!",
            "§c[Aldeano] ¡No necesitamos TUS lecciones!",
            "§c[Aldeano] Fingiendo estar educado...",
            "§7[Aldeano] *se burla*",
            "§c[Aldeano] ¡No puedes enseñarnos nada!",
        ],
    )

    _block(
        en,
        es,
        "anvil",
        [
            "§8[Villager] An anvil! A proper forge!",
            "§a[Villager] You're a blacksmith—excellent!",
            "§7[Villager] We always need skilled metalworkers.",
            "§8[Villager] *nods respectfully*",
            "§a[Villager] Your smithing will serve the village well!",
            "§8[Villager] A master artisan among us!",
        ],
        [
            "§8[Aldeano] ¡Un yunque! ¡Una forja apropiada!",
            "§a[Aldeano] ¡Eres herrero! ¡Excelente!",
            "§7[Aldeano] Siempre necesitamos trabajadores del metal hábiles.",
            "§8[Aldeano] *asiente con respeto*",
            "§a[Aldeano] ¡Tu trabajo de herrería servirá bien a la aldea!",
            "§8[Aldeano] ¡Un maestro artesano entre nosotros!",
        ],
        [
            "§e[Villager] An anvil! You're a smith?",
            "§7[Villager] That's heavy equipment.",
            "§e[Villager] Setting up a forge?",
            "§8[Villager] You work metal?",
            "§e[Villager] Planning to repair tools?",
            "§7[Villager] That'll be useful.",
        ],
        [
            "§e[Aldeano] ¡Un yunque! ¿¡Eres herrero!",
            "§7[Aldeano] Ese es equipo pesado.",
            "§e[Aldeano] ¿¡Preparando una forja!",
            "§8[Aldeano] ¿¡Trabajas el metal!",
            "§e[Aldeano] ¿¡Planeas reparar herramientas!",
            "§7[Aldeano] Eso será útil.",
        ],
        [
            "§c[Villager] Making weapons against us!",
            "§c[Villager] We don't trust you with an anvil!",
            "§c[Villager] You'll forge arms to attack us!",
            "§7[Villager] *eyes the anvil suspiciously*",
            "§c[Villager] Take your forge elsewhere!",
            "§c[Villager] We don't want weapons in OUR village!",
        ],
        [
            "§c[Aldeano] ¿¡Haciendo armas contra nosotros!",
            "§c[Aldeano] ¡No confiamos en ti con un yunque!",
            "§c[Aldeano] ¡Forjarás armas para atacarnos!",
            "§7[Aldeano] *mira el yunque sospechosamente*",
            "§c[Aldeano] ¡Lleva tu forja a otro lugar!",
            "§c[Aldeano] ¡No queremos armas en NUESTRA aldea!",
        ],
    )

    _block(
        en,
        es,
        "grindstone",
        [
            "§7[Villager] A grindstone! Very practical!",
            "§a[Villager] You think of everything!",
            "§7[Villager] Everyone can use that for repairs.",
            "§a[Villager] Community tool stations are always welcome!",
            "§7[Villager] *appreciates the utility*",
        ],
        [
            "§7[Aldeano] ¡Una piedra de afilar! ¡Muy práctico!",
            "§a[Aldeano] ¡Piensas en todo!",
            "§7[Aldeano] Todos podemos usar eso para reparaciones.",
            "§a[Aldeano] ¡Las herramientas comunitarias siempre son bienvenidas!",
            "§7[Aldeano] *aprecia la utilidad*",
        ],
        [
            "§e[Villager] A grindstone! Useful.",
            "§7[Villager] For sharpening and repairs?",
            "§e[Villager] Practical.",
            "§7[Villager] Good for keeping tools sharp.",
            "§e[Villager] Setting up a repair station?",
        ],
        [
            "§e[Aldeano] ¡Una piedra de afilar! Útil.",
            "§7[Aldeano] ¿¡Para afilar y reparar!",
            "§e[Aldeano] Eso es práctico.",
            "§7[Aldeano] Bueno para mantener herramientas.",
            "§e[Aldeano] ¿¡Preparando una estación de reparación!",
        ],
        [
            "§c[Villager] Sharpening weapons, I bet!",
            "§c[Villager] We know what you're planning!",
            "§c[Villager] That's for making swords sharper!",
            "§7[Villager] *watches cautiously*",
            "§c[Villager] Gearing up for violence...",
        ],
        [
            "§c[Aldeano] ¡Afilando armas, apuesto!",
            "§c[Aldeano] ¡Sabemos lo que estás planeando!",
            "§c[Aldeano] ¡Eso es para hacer espadas más afiladas!",
            "§7[Aldeano] *observa con cautela*",
            "§c[Aldeano] Preparándote para la violencia...",
        ],
    )

    _block(
        en,
        es,
        "loom",
        [
            "§d[Villager] A loom! You're a weaver!",
            "§a[Villager] The village needs more artisans!",
            "§7[Villager] Beautiful banners await!",
            "§d[Villager] You'll make wonderful banners!",
            "§a[Villager] A true artist among us!",
        ],
        [
            "§d[Aldeano] ¡Un telar! ¡Eres tejedor!",
            "§a[Aldeano] ¡La aldea necesita más artesanos!",
            "§7[Aldeano] ¡Hermosos tapices nos esperan!",
            "§d[Aldeano] ¡Harás estandartes maravillosos!",
            "§a[Aldeano] ¡Un verdadero artista entre nosotros!",
        ],
        [
            "§e[Villager] A loom! Making banners?",
            "§7[Villager] For weaving patterns?",
            "§e[Villager] That's creative.",
            "§d[Villager] You're artistic!",
            "§e[Villager] Planning decorations?",
        ],
        [
            "§e[Aldeano] ¡Un telar! ¿¡Haces estandartes!",
            "§7[Aldeano] ¿¡Para tejer patrones!",
            "§e[Aldeano] Eso es creativo.",
            "§d[Aldeano] ¿¡Eres artístico!",
            "§e[Aldeano] ¿¡Planeas hacer decoraciones!",
        ],
        [
            "§c[Villager] Making YOUR banners in OUR village!",
            "§c[Villager] We don't want your symbols here!",
            "§c[Villager] Trying to mark this as YOUR territory!",
            "§7[Villager] *strongly disapproves*",
            "§c[Villager] Remove that loom!",
        ],
        [
            "§c[Aldeano] ¿¡Haciendo TUS estandartes en NUESTRA aldea!",
            "§c[Aldeano] ¡No queremos tus símbolos aquí!",
            "§c[Aldeano] ¡Intentas marcar esto como TU territorio!",
            "§7[Aldeano] *desaprueba fuertemente*",
            "§c[Aldeano] ¡Quita ese telar!",
        ],
    )

    _block(
        en,
        es,
        "composter",
        [
            "§2[Villager] A composter! You're farming!",
            "§a[Villager] Excellent! We need more farmers!",
            "§7[Villager] You'll help our crops grow!",
            "§2[Villager] Contributing to our agriculture!",
            "§a[Villager] The fields will thrive!",
        ],
        [
            "§2[Aldeano] ¡Una compostera! ¡Estás cultivando!",
            "§a[Aldeano] ¡Excelente! ¡Necesitamos más granjeros!",
            "§7[Aldeano] ¡Ayudarás a crecer nuestros cultivos!",
            "§2[Aldeano] ¡Contribuyendo a nuestra agricultura!",
            "§a[Aldeano] ¡Los campos prosperarán!",
        ],
        [
            "§e[Villager] A composter! Planning to farm?",
            "§7[Villager] For bone meal?",
            "§2[Villager] Going to grow crops?",
            "§e[Villager] Useful for farming.",
            "§7[Villager] Good for gardens.",
        ],
        [
            "§e[Aldeano] ¡Una compostera! ¿¡Planeas cultivar!",
            "§7[Aldeano] ¿¡Para hacer harina de huesos!",
            "§2[Aldeano] ¿¡Estás cultivando!",
            "§e[Aldeano] Eso es útil para cultivar.",
            "§7[Aldeano] Bueno para los jardines.",
        ],
        [
            "§c[Villager] Stealing our farming methods!",
            "§c[Villager] That's for OUR crops, not yours!",
            "§c[Villager] You'll ruin the soil!",
            "§7[Villager] *protective of the farmland*",
            "§c[Villager] Leave our farming alone!",
        ],
        [
            "§c[Aldeano] ¡Robando nuestros métodos de cultivo!",
            "§c[Aldeano] ¡Eso es para NUESTROS cultivos, no los tuyos!",
            "§c[Aldeano] ¡Arruinarás el suelo!",
            "§7[Aldeano] *protector de las tierras de cultivo*",
            "§c[Aldeano] ¡Deja nuestra agricultura en paz!",
        ],
    )

    _block(
        en,
        es,
        "cauldron",
        [
            "§b[Villager] A cauldron! Very handy!",
            "§a[Villager] Everyone can use that!",
            "§7[Villager] For water storage and washing.",
            "§b[Villager] Practical thinking!",
            "§a[Villager] The village benefits!",
        ],
        [
            "§b[Aldeano] ¡Un caldero! ¡Muy útil!",
            "§a[Aldeano] ¡Todos podemos usar eso!",
            "§7[Aldeano] Para almacenar agua y lavar.",
            "§b[Aldeano] ¡Pensamiento práctico!",
            "§a[Aldeano] ¡La aldea se beneficia de esto!",
        ],
        [
            "§e[Villager] A cauldron! For water?",
            "§7[Villager] Practical to have around.",
            "§b[Villager] Multi-purpose tool.",
            "§e[Villager] For potions or washing?",
            "§7[Villager] Practical.",
        ],
        [
            "§e[Aldeano] ¡Un caldero! ¿¡Para agua!",
            "§7[Aldeano] Eso es práctico tener a mano.",
            "§b[Aldeano] Herramienta multifunción.",
            "§e[Aldeano] ¿¡Para pociones o lavar!",
            "§7[Aldeano] Práctico.",
        ],
        [
            "§c[Villager] What are you brewing in there!?",
            "§c[Villager] Probably making poison!",
            "§c[Villager] Witch! Witch!",
            "§7[Villager] *backs away from the cauldron*",
            "§c[Villager] We don't want dark magic here!",
        ],
        [
            "§c[Aldeano] ¿¡Qué estás preparando ahí!",
            "§c[Aldeano] ¡Probablemente estás haciendo veneno!",
            "§c[Aldeano] ¡Bruja! ¡Bruja!",
            "§7[Aldeano] *retrocede del caldero*",
            "§c[Aldeano] ¡No queremos magia oscura aquí!",
        ],
    )

    _tier(
        en,
        es,
        "generic",
        "welcome",
        [
            "§a[Villager] Building something? Nice!",
            "§a[Villager] Feel free to expand the village!",
            "§7[Villager] *nods approvingly*",
            "§a[Villager] Making improvements!",
            "§a[Villager] You're part of the village now!",
        ],
        [
            "§a[Aldeano] ¿Construyendo algo? ¡Bien!",
            "§a[Aldeano] ¡Siéntete libre de expandir la aldea!",
            "§7[Aldeano] *asiente con aprobación*",
            "§a[Aldeano] ¡Haciendo mejoras!",
            "§a[Aldeano] ¡Ya eres parte de la aldea!",
        ],
    )
    _tier(
        en,
        es,
        "generic",
        "neutral",
        [
            "§e[Villager] Building here?",
            "§e[Villager] What are you up to?",
            "§7[Villager] *watches curiously*",
            "§e[Villager] Adding to the village...",
            "§e[Villager] Hmm, interesting...",
        ],
        [
            "§e[Aldeano] ¿Construyendo aquí?",
            "§e[Aldeano] ¿Qué estás haciendo?",
            "§7[Aldeano] *observa con curiosidad*",
            "§e[Aldeano] Añadiendo a la aldea...",
            "§e[Aldeano] Hmm, interesante...",
        ],
    )
    _tier(
        en,
        es,
        "generic",
        "unwelcome",
        [
            "§c[Villager] Hey! What are you doing!?",
            "§c[Villager] You're not welcome to build here!",
            "§c[Villager] Stop placing blocks in OUR village!",
            "§7[Villager] *glares*",
            "§c[Villager] Take your building elsewhere!",
            "§c[Villager] This is NOT your land!",
        ],
        [
            "§c[Aldeano] ¡Oye! ¿¡Qué haces!?",
            "§c[Aldeano] ¡No eres bienvenido a construir aquí!",
            "§c[Aldeano] ¡Deja de poner bloques en NUESTRA aldea!",
            "§7[Aldeano] *mira con furia*",
            "§c[Aldeano] ¡Vete con tus construcciones!",
            "§c[Aldeano] ¡Esta NO es TU tierra!",
        ],
    )
